Fix quick start link.
dfinity/docs pull request #290
Opened 2021-01-26 12:11 UTC by di-wu

**Overview**
Fixed broken Quick Start link in README.

2021-01-26 12:18 UTC, di-wu commented
This link is broken on multiple locations.

In `docs/modules/developers-guide/pages/tutorials-intro.adoc` for example:

```
../quickstart/quickstart{outfilesuffix}[Quick start]
```

Do I include fixes for these as well?

2021-01-26 21:20 UTC, lsgunnlsgunn commented on modules/ROOT/pages/videos-tutorials.adoc
> +To try it yourself, follow the steps in the link:quickstart/quickstart-intro{outfilesuffix}[Quick start] tutorial.
```suggestion
To try it yourself, follow the steps in the link:quickstart/local-quickstart{outfilesuffix}[Quick start] tutorial.
```

2021-01-26 21:20 UTC, lsgunnlsgunn commented on modules/ROOT/pages/videos-tutorials.adoc
> +The link:quickstart/quickstart-intro{outfilesuffix}[Quick start] provides a simplified introduction to the basic work flow for creating and deploying a new project without exploring the contents of t
```suggestion
The link:quickstart/local-quickstart{outfilesuffix}[Quick start] provides a simplified introduction to the basic work flow for creating and deploying a new project without exploring the contents of the project directory or sample code.
```

2021-01-26 21:20 UTC, lsgunnlsgunn commented on modules/developers-guide/pages/install-upgrade-remove.adoc
> +As described in the link:../quickstart/quickstart-intro{outfilesuffix}[Quick start], you can download and install the latest version of the {sdk-short-name} package by running a command in a terminal
```suggestion
As described in the link:../quickstart/local-quickstart{outfilesuffix}[Quick start], you can download and install the latest version of the {sdk-short-name} package by running a command in a terminal shell.
```

2021-01-26 21:20 UTC, lsgunnlsgunn commented on modules/developers-guide/pages/lang-service-ide.adoc
> +For information about installing the plugin, see link:../quickstart/quickstart-intro{outfilesuffix}#install-vscode[Install the language editor plug-in].
```suggestion
For information about installing the plugin, see link:../quickstart/local-quickstart{outfilesuffix}#install-vscode[Install the language editor plug-in].
```

2021-01-26 21:20 UTC, lsgunnlsgunn commented on modules/developers-guide/pages/tutorials/access-control.adoc
> +* You have downloaded and installed the {sdk-short-name} package as described in link:../../quickstart/quickstart-intro{outfilesuffix}#download-and-install[Download and install].
```suggestion
* You have downloaded and installed the {sdk-short-name} package as described in link:../../quickstart/local-quickstart{outfilesuffix}#download-and-install[Download and install].
```

2021-01-26 21:20 UTC, lsgunnlsgunn commented on modules/developers-guide/pages/tutorials/access-control.adoc
> +* You have installed the Visual Studio Code plugin for {proglang} as described in link:../../quickstart/quickstart-intro{outfilesuffix}#install-vscode[Install the language editor plug-in] if you are
```suggestion
* You have installed the Visual Studio Code plugin for {proglang} as described in link:../../quickstart/local-quickstart{outfilesuffix}#install-vscode[Install the language editor plug-in] if you are using Visual Studio Code as your IDE.
```

2021-01-26 21:20 UTC, lsgunnlsgunn commented on modules/developers-guide/pages/tutorials/calculator.adoc
> +* You have downloaded and installed the {sdk-short-name} package as described in link:../../quickstart/quickstart-intro{outfilesuffix}#download-and-install[Download and install].
```suggestion
* You have downloaded and installed the {sdk-short-name} package as described in link:../../quickstart/loal-quickstart{outfilesuffix}#download-and-install[Download and install].
```

2021-01-26 21:20 UTC, lsgunnlsgunn commented on modules/developers-guide/pages/tutorials/counter-tutorial.adoc
> +* You have downloaded and installed the {sdk-short-name} package as described in link:../../quickstart/quickstart-intro{outfilesuffix}#download-and-install[Download and install].
```suggestion
* You have downloaded and installed the {sdk-short-name} package as described in link:../../quickstart/local-quickstart{outfilesuffix}#download-and-install[Download and install].
```

2021-01-26 21:20 UTC, lsgunnlsgunn commented on modules/developers-guide/pages/tutorials/custom-frontend.adoc
> +* You have downloaded and installed the {sdk-short-name} package as described in link:../../quickstart/quickstart-intro{outfilesuffix}#download-and-install[Download and install].
```suggestion
* You have downloaded and installed the {sdk-short-name} package as described in link:../../quickstart/local-quickstart{outfilesuffix}#download-and-install[Download and install].
```

2021-01-26 21:20 UTC, lsgunnlsgunn commented on modules/developers-guide/pages/tutorials/custom-frontend.adoc
> +* You have installed the Visual Studio Code plugin for {proglang} as described in link:../../quickstart/quickstart-intro{outfilesuffix}#install-vscode[Install the language editor plug-in] if you are
```suggestion
* You have installed the Visual Studio Code plugin for {proglang} as described in link:../../quickstart/local-quickstart{outfilesuffix}#install-vscode[Install the language editor plug-in] if you are using Visual Studio Code as your IDE.
```

2021-01-26 21:20 UTC, lsgunnlsgunn commented on modules/developers-guide/pages/tutorials/define-an-actor.adoc
> +* You have downloaded and installed the {sdk-short-name} package as described in link:../../quickstart/quickstart-intro{outfilesuffix}#download-and-install[Download and install].
```suggestion
* You have downloaded and installed the {sdk-short-name} package as described in link:../../quickstart/local-quickstart{outfilesuffix}#download-and-install[Download and install].
```

2021-01-26 21:20 UTC, lsgunnlsgunn commented on modules/developers-guide/pages/tutorials/explore-templates.adoc
> +* You have downloaded and installed the {sdk-short-name} package as described in link:../../quickstart/quickstart-intro{outfilesuffix}#download-and-install[Download and install].
```suggestion
* You have downloaded and installed the {sdk-short-name} package as described in link:../../quickstart/local-quickstart{outfilesuffix}#download-and-install[Download and install].
```

2021-01-26 21:20 UTC, lsgunnlsgunn commented on modules/developers-guide/pages/tutorials/explore-templates.adoc
> +* You have installed the Visual Studio Code plugin for {proglang} as described in link:../../quickstart/quickstart-intro{outfilesuffix}#install-vscode[Install the language editor plug-in] if you are
```suggestion
* You have installed the Visual Studio Code plugin for {proglang} as described in link:../../quickstart/local-quickstart{outfilesuffix}#install-vscode[Install the language editor plug-in] if you are using Visual Studio Code as your IDE.
```

2021-01-26 21:20 UTC, lsgunnlsgunn commented on modules/developers-guide/pages/tutorials/hello-location.adoc
> +* You have downloaded and installed the {sdk-short-name} package as described in link:../../quickstart/quickstart-intro{outfilesuffix}#download-and-install[Download and install].
```suggestion
* You have downloaded and installed the {sdk-short-name} package as described in link:../../quickstart/local-quickstart{outfilesuffix}#download-and-install[Download and install].
```

2021-01-26 21:20 UTC, lsgunnlsgunn commented on modules/developers-guide/pages/tutorials/intercanister-calls.adoc
> +* You have downloaded and installed the {sdk-short-name} package as described in link:../../quickstart/quickstart-intro{outfilesuffix}#download-and-install[Download and install].
```suggestion
* You have downloaded and installed the {sdk-short-name} package as described in link:../../quickstart/local-quickstart{outfilesuffix}#download-and-install[Download and install].
```

2021-01-26 21:20 UTC, lsgunnlsgunn commented on modules/developers-guide/pages/tutorials/multiple-actors.adoc
> +* You have downloaded and installed the {sdk-short-name} package as described in link:../../quickstart/quickstart-intro{outfilesuffix}#download-and-install[Download and install].
```suggestion
* You have downloaded and installed the {sdk-short-name} package as described in link:../../quickstart/local-quickstart{outfilesuffix}#download-and-install[Download and install].
```

2021-01-26 21:20 UTC, lsgunnlsgunn commented on modules/developers-guide/pages/tutorials/my-contacts.adoc
> +* You have downloaded and installed the {sdk-short-name} package as described in link:../../quickstart/quickstart-intro{outfilesuffix}#download-and-install[Download and install].
```suggestion
* You have downloaded and installed the {sdk-short-name} package as described in link:../../quickstart/local-quickstart{outfilesuffix}#download-and-install[Download and install].
```

2021-01-26 21:20 UTC, lsgunnlsgunn commented on modules/developers-guide/pages/tutorials/my-contacts.adoc
> +* You have installed the Visual Studio Code plugin for {proglang} as described in link:../../quickstart/quickstart-intro{outfilesuffix}#install-vscode[Install the language editor plug-in] if you are
```suggestion
* You have installed the Visual Studio Code plugin for {proglang} as described in link:../../quickstart/local-quickstart{outfilesuffix}#install-vscode[Install the language editor plug-in] if you are using Visual Studio Code as your IDE.
```

2021-01-26 21:20 UTC, lsgunnlsgunn commented on modules/developers-guide/pages/tutorials/phonebook.adoc
> +* You have downloaded and installed the {sdk-short-name} package as described in link:../../quickstart/quickstart-intro{outfilesuffix}#download-and-install[Download and install].
```suggestion
* You have downloaded and installed the {sdk-short-name} package as described in link:../../quickstart/local-quickstart{outfilesuffix}#download-and-install[Download and install].
```

2021-01-26 21:22 UTC, lsgunnlsgunn requested changes
Some links need to go to a quickstart scenario rather than the intro

2021-01-26 23:38 UTC, lsgunnlsgunn commented
Thanks for catching t˙ese broken links and typos. I've integrated your fixes in a different PR:
https://github.com/dfinity/docs/pull/292

2021-01-26 23:38 UTC, closed without merging

2021-01-27 08:48 UTC, di-wu commented
Alright, thanks @lsgunnlsgunn!